<?php

namespace AppBundle\Repository;

/**
 * SetOfDishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetOfDishRepository extends \Doctrine\ORM\EntityRepository
{
}
