<?php

namespace AppBundle\Repository;

/**
 * SoupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoupRepository extends \Doctrine\ORM\EntityRepository
{
}
